### PR TITLE
Added volume and back button functionality

### PR DESCRIPTION
**Pull request by bartulo**
I added volume functionality (I created a new method in KodiMethods class), and also created Back button functionality in keypad number 4.
Great project by the way.

### CODE REVIEW

**Comment by sunsetsonwheels** [comment]
Hi, I'm very thankful for your pull request. Lately I haven't had much time to work on this project as I would have liked (IGCSE trial exams).


Here are the things I've changed from your PR:


- Since the back button used to be assigned to the Answer call key in Kaidi Remote (Alpha), I have removed key number 4 on the main remote and assigned the Answer call key to the back function (muscle memory reasons). This decision is also based on the fact that on landscape KaiOS phones, there is a lack of vertical space, and I have already put the info label for the Answer key in the main remote beforehand; however, I have something brewing up already to address this issue ;) I hope you don't mind this slight change.


Again, thank you very very much for your pull request. I'm very new to handling these, so please do pardon me if mistakes were made :)

I guess if you are fine with it I will merge the PR with master.

**Comment by bartulo** [comment]
This is my very first pull request in github ever, so we are both new in this. I'll be very grateful if you merge the pr with the changes you need to make.

**Comment by bartulo** [comment]
This is my very first pull request in github ever, so we are both new in this. I'll be very grateful if you merge the pr with the changes you need to make.

**Comment by sunsetsonwheels** [comment]
I have merged it. Thank you very much :)

**Comment by bartulo** [comment]
That's great. Thank you.

**Pull request merged**
